import { source } from '@/lib/source';
import { createFromSource } from 'fumadocs-core/search/server';
import type { StructuredData } from 'fumadocs-core/mdx-plugins';
import { findPath } from 'fumadocs-core/page-tree';
// Generated by scripts/build-search-index.mjs (runs on postinstall and build)
import structuredDataByPath from '@/.source/search-structured-data.json';

// JSON drops `heading: undefined`, so it needs widening to the real type
const structuredData = structuredDataByPath as unknown as Record<string, StructuredData>;

export const { GET } = createFromSource(source, {
  // https://docs.orama.com/docs/orama-js/supported-languages
  language: 'english',
  // Use precomputed structured data instead of compiling every MDX page (async pages would
  // otherwise all be compiled on the first search, which takes ~30s)
  buildIndex(page) {
    const pageTree = source.getPageTree();
    const path = findPath(
      pageTree.children,
      (node) => node.type === 'page' && node.url === page.url,
    );
    path?.pop();
    const breadcrumbs = [pageTree.name, ...(path ?? []).map((node) => node.name)].filter(
      (name): name is string => typeof name === 'string' && name.length > 0,
    );

    return {
      id: page.url,
      url: page.url,
      title: page.data.title,
      description: page.data.description,
      breadcrumbs,
      structuredData: structuredData[page.path],
    };
  },
});
